# Train Test Split in Machine Learning

**Import Libary**

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

**Dataset**

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

**Separat value in train and test**

train_test_split(x,y) have a 4 catagary
* x value train
* x value test
* y value train
* y value test

First come x values and after come y values and That's wahy first come train value

test_size value between 0 & 1
* Ex - if test_size =0.2 x_train is 0.8

'random_state' mkethod use in Maintaining the same data set <br>
'shuffle = False' method use in data shuffle or not

In [3]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.25)

**X Values**

Choose x_train values (Ramdomly)

In [4]:
x_train

array([19, 15, 18,  1,  4,  9, 14,  3, 10,  6, 13, 12,  5, 11,  2])

Look at length of x_train

In [5]:
len(x_train)

15

Choose x_test values (Ramdomly)

In [6]:
x_test

array([17, 16,  7, 20,  8])

Look at length of x_test

In [7]:
len(x_test)

5

**Y Values**

Choose y_train values (Ramdomly)

In [8]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0])

Look at length of y_train

In [9]:
len(y_train)

15

Choose y_test values (Ramdomly)

In [10]:
y_test

array([1, 0, 0, 1, 0])

Look at length of y_test

In [11]:
len(x_test)

5