# K-Nearest Neighbors Algorithm

In [1]:
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv('/DataSets/Iris.csv')
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
# Last 5 rows
data.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

### Data Shape

In [6]:
data.shape

(150, 6)

### Species Column data value count

In [7]:
data['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

### Information of data set

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [9]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

x = SepalLengthCm,	SepalWidthCm,	PetalLengthCm,	PetalWidthCm
Y = Species

iloc --> Index Location
: --> Should be all row use
1:5 --> coulumn between take 1 to 4

## x data values

In [10]:
x = data.iloc[:,1:5]
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

###  y data values


In [11]:
y = data.iloc[:,-1] # -1 --> Last Column
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

### x values is Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [13]:
x = scaler.fit_transform(x)
x[0:5] # Show between 1 to 5 values

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

### Devide Train and Test in data set

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [15]:
x_train.shape # Show x_train data shape

(120, 4)

In [17]:
x_test.shape # Show x_train data shape

(30, 4)

## Model Train Use K-Nearest Neighbors Algorithm

In [18]:
# import KNeighborsClassifier using sklearn.neighbors class
from sklearn.neighbors import KNeighborsClassifier
#Create obgect using  KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1) # n_neighbors is K value
model.fit(x_train,y_train) # Train model using x_train,y_train data sets

KNeighborsClassifier(n_neighbors=1)

### Using Model

In [19]:
pred = model.predict(x_test) # Predict using x_test data set
pred[0:5] # Get predict first 5 value (Predict values)

array(['Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor'], dtype=object)

In [20]:
y_test[0:5] # Get y_test first 5 value (Actual Value)

4         Iris-setosa
33        Iris-setosa
92    Iris-versicolor
60    Iris-versicolor
73    Iris-versicolor
Name: Species, dtype: object

### Look at Model Accurancy

**using sklearn.metricsclass**

In [21]:
# import ccuracy_score using sklearn.metricsclass
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred) # Give Y accual value and Model predict value
accuracy

0.9333333333333333

In [24]:
# import confusion_matrix using sklearn.metrics
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,pred) # Give Y accual value and Model predict value
cm

array([[11,  0,  0],
       [ 0,  8,  1],
       [ 0,  1,  9]])

### Accurancy Details

In [25]:
# Look at Accual value and Predict value in Y
result = pd.DataFrame(data=[y_test.values,pred],index=['Y_test','Pred'])
result.transpose()

Y_test             Pred
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2   Iris-versicolor  Iris-versicolor
3   Iris-versicolor  Iris-versicolor
4   Iris-versicolor  Iris-versicolor
5       Iris-setosa      Iris-setosa
6       Iris-setosa      Iris-setosa
7    Iris-virginica   Iris-virginica
8   Iris-versicolor  Iris-versicolor
9       Iris-setosa      Iris-setosa
10   Iris-virginica   Iris-virginica
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13  Iris-versicolor  Iris-versicolor
14   Iris-virginica   Iris-virginica
15   Iris-virginica   Iris-virginica
16   Iris-virginica  Iris-versicolor
17   Iris-virginica   Iris-virginica
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20   Iris-virginica   Iris-virginica
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24  Iris-versicolor  Iris-versicolor
25      Iris-setosa      Iris-setosa
26  Iris-versicolor  Iris-versicolor
27      Iris-setosa      Iris-setosa
28   Iris-virginica   Iris-virginica
29  Iris-versicolor   Iris-virginica

### Choose Currect K value

In [26]:
correct_sum = [] # make list in currect_sum
for i in range(1,21): # Seacrch for K value between 1 to 20
  model = KNeighborsClassifier(n_neighbors=i) # create Object  KNeighborsClassifie and K value = (n_neighbors=i
  model.fit(x_train,y_train) # Train Model
  pred = model.predict(x_test)
  correct = np.sum(pred == y_test) # if predict value eqlual to accual value
  correct_sum.append(correct) # Sum Correct

In [27]:
correct_sum

[28,
 27,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28,
 28]

K=1 --> 28, K=2 --> 27, K=3 --> 28, K=4 --> 28, K=5 --->28 ............. (30 n)

**Using Data Frame**

In [29]:
result = pd.DataFrame(data=correct_sum)
result.index = result.index + 1
result

0
1   28
2   27
3   28
4   28
5   28
6   28
7   28
8   28
9   28
10  28
11  28
12  28
13  28
14  28
15  28
16  28
17  28
18  28
19  28
20  28

### If K = 8

In [30]:
model = KNeighborsClassifier(n_neighbors=8) # create Object  KNeighborsClassifie and K value is 8
model.fit(x_train,y_train) # Train Model
pred = model.predict(x_test)

**Accurancy**

In [32]:
accuracy_score(y_test, pred) # Look at accurancy

0.9333333333333333

In [33]:
confusion_matrix(y_test, pred) # Look at confusion matrix

array([[11,  0,  0],
       [ 0,  8,  1],
       [ 0,  1,  9]])